"""add_permission_for_Role

Revision ID: 19699146d4e5
Revises: 3ed70c9aac80
Create Date: 2015-12-01 19:13:59.795803

"""

# revision identifiers, used by Alembic.
revision = '19699146d4e5'
down_revision = '3ed70c9aac80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('blog_role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blog_role_default'), 'blog_role', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_role_default'), table_name='blog_role')
    op.drop_column('blog_role', 'permissions')
    op.drop_column('blog_role', 'default')
    ### end Alembic commands ###
