"""add Role

Revision ID: 2016c097d809
Revises: 28b6e67ca082
Create Date: 2015-11-24 15:14:00.349196

"""

# revision identifiers, used by Alembic.
revision = '2016c097d809'
down_revision = '28b6e67ca082'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.add_column(u'blog_user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_user', 'blog_role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_user', type_='foreignkey')
    op.drop_column(u'blog_user', 'role_id')
    op.drop_table('blog_role')
    ### end Alembic commands ###
