"""add body_html filed for Post

Revision ID: 30743a3b7fe3
Revises: 3029759cde88
Create Date: 2015-12-11 10:43:21.594559

"""

# revision identifiers, used by Alembic.
revision = '30743a3b7fe3'
down_revision = '3029759cde88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'body_html')
    ### end Alembic commands ###
