"""add disabled,audited filed for Comment

Revision ID: 33082c00895b
Revises: 3828b73f7617
Create Date: 2015-12-16 19:04:05.350299

"""

# revision identifiers, used by Alembic.
revision = '33082c00895b'
down_revision = '3828b73f7617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('audited', sa.Boolean(), nullable=True))
    op.add_column('blog_comment', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_comment', 'disabled')
    op.drop_column('blog_comment', 'audited')
    ### end Alembic commands ###
