"""add confirmed field for User

Revision ID: 3ed70c9aac80
Revises: 9395b558e00
Create Date: 2015-11-26 17:43:30.125184

"""

# revision identifiers, used by Alembic.
revision = '3ed70c9aac80'
down_revision = '9395b558e00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_user', 'confirmed')
    ### end Alembic commands ###
