"""set email unique

Revision ID: 9395b558e00
Revises: 2016c097d809
Create Date: 2015-11-25 18:49:22.973272

"""

# revision identifiers, used by Alembic.
revision = '9395b558e00'
down_revision = '2016c097d809'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blog_user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_user', type_='unique')
    ### end Alembic commands ###
